// <auto-generated />
using System;
using EducationProcess.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EducationProcess.DataAccess.Migrations
{
    [DbContext(typeof(EducationProcessContext))]
    [Migration("20210815194937_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Utf8_General_Ci")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.AcademicYear", b =>
                {
                    b.Property<int>("AcademicYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Academic_year_id");

                    b.Property<short>("BeginingYear")
                        .HasColumnType("smallint")
                        .HasColumnName("Begining_year");

                    b.Property<short>("EndingYear")
                        .HasColumnType("smallint")
                        .HasColumnName("Ending_year");

                    b.HasKey("AcademicYearId");

                    b.ToTable("Academic_years");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Audience", b =>
                {
                    b.Property<int>("AudienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Audience_id");

                    b.Property<int?>("AudienceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Audience_type_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Department_id");

                    b.Property<int?>("EmployeeHeadId")
                        .HasColumnType("int")
                        .HasColumnName("Employee_head_id");

                    b.Property<string>("Name")
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<short?>("SeatsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("Seats_count");

                    b.HasKey("AudienceId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "AudienceTypeId" }, "IX_Audiences_Audience_type_id");

                    b.HasIndex(new[] { "EmployeeHeadId" }, "IX_Audiences_Employee_head_id");

                    b.ToTable("Audiences");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.AudienceType", b =>
                {
                    b.Property<int>("AudienceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Audience_type_id");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AudienceTypeId");

                    b.ToTable("Audience_types");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Cathedra", b =>
                {
                    b.Property<int>("CathedraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cathedra_id");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("NameAbbreviation")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Name_abbreviation");

                    b.HasKey("CathedraId");

                    b.ToTable("Cathedras");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.CathedraSpecialty", b =>
                {
                    b.Property<int>("CathedraId")
                        .HasColumnType("int")
                        .HasColumnName("Cathedra_id");

                    b.Property<int>("FsesCategoryPartitionId")
                        .HasColumnType("int")
                        .HasColumnName("Fses_category_partition_id");

                    b.HasKey("CathedraId", "FsesCategoryPartitionId");

                    b.HasIndex(new[] { "FsesCategoryPartitionId" }, "IX_Cathedra_specialties_Specialtie_id");

                    b.ToTable("Cathedra_specialties");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("City_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("Region_id");

                    b.HasKey("CityId");

                    b.HasIndex("RegionId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ConductedPair", b =>
                {
                    b.Property<int>("ConductedPairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Conducted_pair_id");

                    b.Property<int>("LessonTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Lesson_type_id");

                    b.Property<int?>("ScheduleDisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("Schedule_discipline_id");

                    b.Property<int?>("ScheduleDisciplineReplacementId")
                        .HasColumnType("int")
                        .HasColumnName("Schedule_discipline_replacement_id");

                    b.HasKey("ConductedPairId");

                    b.HasIndex(new[] { "LessonTypeId" }, "IX_Conducted_pairs_Lesson_type_id");

                    b.HasIndex(new[] { "ScheduleDisciplineId" }, "IX_Conducted_pairs_Schedule_discipline_id");

                    b.HasIndex(new[] { "ScheduleDisciplineReplacementId" }, "IX_Conducted_pairs_Schedule_discipline_replacement_id");

                    b.ToTable("Conducted_pairs");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Department_id");

                    b.Property<byte?>("BuildingNumber")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("Building_number");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("House_number")
                        .IsFixedLength(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("int")
                        .HasColumnName("Postal_code");

                    b.Property<int>("StreetId")
                        .HasColumnType("int")
                        .HasColumnName("Street_id");

                    b.HasKey("DepartmentId");

                    b.HasIndex("StreetId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Discipline_id");

                    b.Property<int?>("CathedraId")
                        .HasColumnType("int")
                        .HasColumnName("Cathedra_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DisciplineIndex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Discipline_index");

                    b.Property<int>("EducationCycleId")
                        .HasColumnType("int")
                        .HasColumnName("Education_cycle_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)");

                    b.HasKey("DisciplineId");

                    b.HasIndex(new[] { "CathedraId" }, "IX_Disciplines_Cathedra_id");

                    b.HasIndex(new[] { "EducationCycleId" }, "IX_Disciplines_Education_cycle_id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EducationCyclesAndModule", b =>
                {
                    b.Property<int>("EducationCycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Education_cycle_id");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("EducationCycleIndex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Education_cycle_index");

                    b.Property<int?>("EducationCycleParentId")
                        .HasColumnType("int")
                        .HasColumnName("Education_cycle_parent_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("EducationCycleId");

                    b.HasIndex(new[] { "EducationCycleParentId" }, "IX_Education_cycles_and_modules_Education_cycle_parent_id");

                    b.ToTable("Education_cycles_and_modules");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EducationForm", b =>
                {
                    b.Property<int>("EducationFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Education_form_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EducationFormId");

                    b.ToTable("Education_forms");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EducationLevel", b =>
                {
                    b.Property<int>("EducationLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Education_level_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EducationLevelId");

                    b.ToTable("Education_levels");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EducationPlan", b =>
                {
                    b.Property<int>("EducationPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Education_plan_id");

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int")
                        .HasColumnName("Academic_year_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("FsesCategoryPartitionId")
                        .HasColumnType("int")
                        .HasColumnName("Fses_category_partition_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)");

                    b.HasKey("EducationPlanId");

                    b.HasIndex(new[] { "AcademicYearId" }, "IX_Education_plans_Academic_year_id");

                    b.HasIndex(new[] { "FsesCategoryPartitionId" }, "IX_Education_plans_Specialtie_id");

                    b.ToTable("Education_plans");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EducationPlanSemesterDiscipline", b =>
                {
                    b.Property<int>("EducationPlanId")
                        .HasColumnType("int")
                        .HasColumnName("Education_plan_id");

                    b.Property<int>("SemesterDisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("Semester_discipline_id");

                    b.HasKey("EducationPlanId", "SemesterDisciplineId");

                    b.HasIndex(new[] { "SemesterDisciplineId" }, "IX_Education_plan_semester_disciplines_Semester_discipline_id");

                    b.ToTable("Education_plan_semester_disciplines");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Employee_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Department_id");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Middlename")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("Post_id");

                    b.Property<Guid?>("Rowguid")
                        .HasColumnType("char(36)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "PostId" }, "IX_Employees_Post_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EmployeeCathedra", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Employee_id");

                    b.Property<int>("CathedraId")
                        .HasColumnType("int")
                        .HasColumnName("Cathedra_id");

                    b.HasKey("EmployeeId", "CathedraId");

                    b.HasIndex(new[] { "CathedraId" }, "IX_Employee_cathedras_Cathedra_id");

                    b.ToTable("Employee_cathedras");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.FederalStateEducationalStandard", b =>
                {
                    b.Property<int>("FsesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Fses_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<short>("Number")
                        .HasColumnType("smallint");

                    b.HasKey("FsesId");

                    b.ToTable("Federal_state_educational_standards");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.FixedDiscipline", b =>
                {
                    b.Property<int>("FixedDisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Fixed_discipline_id");

                    b.Property<string>("CommentByFixerEmployee")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)")
                        .HasColumnName("Comment_by_fixer_employee");

                    b.Property<string>("CommentByFixingEmployee")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)")
                        .HasColumnName("Comment_by_fixing_employee");

                    b.Property<DateTime?>("CoordinatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Coordinated_at")
                        .HasDefaultValueSql("('2021-07-29T21:04:33.948')");

                    b.Property<int>("FixerEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Fixer_employee_id");

                    b.Property<int>("FixingEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Fixing_employee_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("Group_id");

                    b.Property<bool?>("IsAgreed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_agreed");

                    b.Property<bool?>("IsWatched")
                        .IsRequired()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_watched");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Published_at");

                    b.Property<int>("SemesterDisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("Semester_discipline_id");

                    b.HasKey("FixedDisciplineId");

                    b.HasIndex(new[] { "FixingEmployeeId" }, "IX_Fixed_disciplines_Employee_id");

                    b.HasIndex(new[] { "FixerEmployeeId" }, "IX_Fixed_disciplines_Fixer_employee_id");

                    b.HasIndex(new[] { "GroupId" }, "IX_Fixed_disciplines_Group_id");

                    b.HasIndex(new[] { "SemesterDisciplineId" }, "IX_Fixed_disciplines_Semester_discipline_id");

                    b.ToTable("Fixed_disciplines");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.FsesCategory", b =>
                {
                    b.Property<int>("FsesCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Fses_category_id");

                    b.Property<int>("FsesId")
                        .HasColumnType("int")
                        .HasColumnName("Fses_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<short>("Number")
                        .HasColumnType("smallint");

                    b.HasKey("FsesCategoryId");

                    b.HasIndex(new[] { "FsesId" }, "IX_Fses_categories_Fses_id");

                    b.ToTable("Fses_categories");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.FsesCategoryPartition", b =>
                {
                    b.Property<int>("FsesCategoryPartitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Fses_category_partition_id");

                    b.Property<int>("FirstPartNumber")
                        .HasColumnType("int")
                        .HasColumnName("First_part_number");

                    b.Property<int>("FsesCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Fses_category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NameAbbreviation")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("Name_abbreviation")
                        .IsFixedLength(true);

                    b.Property<int>("SecondPartNumber")
                        .HasColumnType("int")
                        .HasColumnName("Second_part_number");

                    b.Property<short?>("ThirdPathNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("Third_path_number");

                    b.HasKey("FsesCategoryPartitionId");

                    b.HasIndex(new[] { "FsesCategoryId" }, "IX_Fses_category_partitions_Fses_category_id");

                    b.ToTable("Fses_category_partitions");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Group_id");

                    b.Property<byte>("CourseNumber")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("Course_number");

                    b.Property<int?>("CuratorId")
                        .HasColumnType("int")
                        .HasColumnName("Curator_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Department_id");

                    b.Property<int?>("EducationPlanId")
                        .HasColumnType("int")
                        .HasColumnName("Education_plan_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<short>("ReceiptYear")
                        .HasColumnType("smallint")
                        .HasColumnName("Receipt_year");

                    b.Property<int>("ReceivedEducationId")
                        .HasColumnType("int")
                        .HasColumnName("Received_education_id");

                    b.HasKey("GroupId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "CuratorId" }, "IX_Groups_Curator_id");

                    b.HasIndex(new[] { "EducationPlanId" }, "IX_Groups_Education_plan_id");

                    b.HasIndex(new[] { "ReceivedEducationId" }, "IX_Groups_Received_education_id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.IntermediateCertificationForm", b =>
                {
                    b.Property<int>("CertificationFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Certification_form_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CertificationFormId");

                    b.ToTable("Intermediate_certification_forms");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.LessonType", b =>
                {
                    b.Property<int>("LessonTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Lesson_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)");

                    b.HasKey("LessonTypeId");

                    b.ToTable("Lesson_types");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Post_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)");

                    b.HasKey("PostId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ReceivedEducation", b =>
                {
                    b.Property<int>("ReceivedEducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Received_education_id");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("int")
                        .HasColumnName("Education_level_id");

                    b.Property<bool>("IsBudget")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_budget");

                    b.Property<int>("ReceivedEducationFormId")
                        .HasColumnType("int")
                        .HasColumnName("Received_education_form_id");

                    b.Property<int>("ReceivedSpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("Received_specialty_id");

                    b.Property<short>("StudyPeriodMonths")
                        .HasColumnType("smallint")
                        .HasColumnName("Study_period_months");

                    b.HasKey("ReceivedEducationId");

                    b.HasIndex(new[] { "EducationLevelId" }, "IX_Received_educations_Education_level_id");

                    b.HasIndex(new[] { "ReceivedEducationFormId" }, "IX_Received_educations_Received_education_form_id");

                    b.HasIndex(new[] { "ReceivedSpecialtyId" }, "IX_Received_educations_Received_specialty_id");

                    b.ToTable("Received_educations");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ReceivedEducationForm", b =>
                {
                    b.Property<int>("ReceivedEducationFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Received_education_form_id");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("Additional_info");

                    b.Property<int>("EducationFormId")
                        .HasColumnType("int")
                        .HasColumnName("Education_form_id");

                    b.HasKey("ReceivedEducationFormId");

                    b.HasIndex(new[] { "EducationFormId" }, "IX_Received_education_forms_Education_form_id");

                    b.ToTable("Received_education_forms");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ReceivedSpecialty", b =>
                {
                    b.Property<int>("ReceivedSpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Received_specialty_id");

                    b.Property<int>("FsesCategoryPartitionId")
                        .HasColumnType("int")
                        .HasColumnName("Fses_category_partition_id");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ReceivedSpecialtyId");

                    b.HasIndex(new[] { "FsesCategoryPartitionId" }, "IX_Received_specialties_Specialtie_id");

                    b.ToTable("Received_specialties");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Region_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ScheduleDiscipline", b =>
                {
                    b.Property<int>("ScheduleDisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Schedule_discipline_id");

                    b.Property<int?>("AudienceId")
                        .HasColumnType("int")
                        .HasColumnName("Audience_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<int>("CreatedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Created_by_employee_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("FixedDisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("Fixed_discipline_id");

                    b.Property<bool?>("IsEvenPair")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_even_pair");

                    b.Property<bool?>("IsFirstSubgroup")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_first_subgroup");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Modified_at");

                    b.Property<int>("ModifiedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Modified_by_employee_id");

                    b.Property<int>("PairNumber")
                        .HasColumnType("int")
                        .HasColumnName("Pair_number");

                    b.HasKey("ScheduleDisciplineId");

                    b.HasIndex(new[] { "AudienceId" }, "IX_Schedule_disciplines_Audience_id");

                    b.HasIndex(new[] { "CreatedByEmployeeId" }, "IX_Schedule_disciplines_Created_by_employee_id");

                    b.HasIndex(new[] { "FixedDisciplineId" }, "IX_Schedule_disciplines_Fixed_discipline_id");

                    b.HasIndex(new[] { "ModifiedByEmployeeId" }, "IX_Schedule_disciplines_Modified_by_employee_id");

                    b.ToTable("Schedule_disciplines");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ScheduleDisciplineReplacement", b =>
                {
                    b.Property<int>("ScheduleDisciplineReplacementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Schedule_discipline_replacement_id");

                    b.Property<int?>("AudienceId")
                        .HasColumnType("int")
                        .HasColumnName("Audience_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<int>("CreatedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Created_by_employee_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("FixedDisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("Fixed_discipline_id");

                    b.Property<bool?>("IsFirstSubgroup")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_first_subgroup");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Modified_at");

                    b.Property<int>("ModifiedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Modified_by_employee_id");

                    b.Property<int>("PairNumber")
                        .HasColumnType("int")
                        .HasColumnName("Pair_number");

                    b.Property<int?>("ScheduleDisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("Schedule_discipline_id");

                    b.HasKey("ScheduleDisciplineReplacementId");

                    b.HasIndex(new[] { "AudienceId" }, "IX_Schedule_discipline_replacement_Audience_id");

                    b.HasIndex(new[] { "CreatedByEmployeeId" }, "IX_Schedule_discipline_replacement_Created_by_employee_id");

                    b.HasIndex(new[] { "FixedDisciplineId" }, "IX_Schedule_discipline_replacement_Fixed_discipline_id");

                    b.HasIndex(new[] { "ModifiedByEmployeeId" }, "IX_Schedule_discipline_replacement_Modified_by_employee_id");

                    b.HasIndex(new[] { "ScheduleDisciplineId" }, "IX_Schedule_discipline_replacement_Schedule_discipline_id");

                    b.ToTable("Schedule_discipline_replacement");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Semester_id");

                    b.Property<byte>("Number")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("WeeksCount")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("Weeks_count");

                    b.HasKey("SemesterId");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.SemesterDiscipline", b =>
                {
                    b.Property<int>("SemesterDisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Semester_discipline_id");

                    b.Property<int?>("CertificationFormId")
                        .HasColumnType("int")
                        .HasColumnName("Certification_form_id");

                    b.Property<short>("ConsultationHours")
                        .HasColumnType("smallint")
                        .HasColumnName("Consultation_hours");

                    b.Property<short>("ControlWorkHours")
                        .HasColumnType("smallint")
                        .HasColumnName("Control_work_hours");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("Discipline_id");

                    b.Property<short>("EducationalPracticeHours")
                        .HasColumnType("smallint")
                        .HasColumnName("Educational_practice_hours");

                    b.Property<short>("ExamHours")
                        .HasColumnType("smallint")
                        .HasColumnName("Exam_hours");

                    b.Property<short>("IndependentWorkHours")
                        .HasColumnType("smallint")
                        .HasColumnName("Independent_work_hours");

                    b.Property<short>("LaboratoryWorkHours")
                        .HasColumnType("smallint")
                        .HasColumnName("Laboratory_work_hours");

                    b.Property<short>("PracticeWorkHours")
                        .HasColumnType("smallint")
                        .HasColumnName("Practice_work_hours");

                    b.Property<short>("ProductionPracticeHours")
                        .HasColumnType("smallint")
                        .HasColumnName("Production_practice_hours");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("Semester_id");

                    b.Property<short>("TheoryLessonHours")
                        .HasColumnType("smallint")
                        .HasColumnName("Theory_lesson_hours");

                    b.HasKey("SemesterDisciplineId");

                    b.HasIndex(new[] { "CertificationFormId" }, "IX_Semester_disciplines_Certification_form_id");

                    b.HasIndex(new[] { "DisciplineId" }, "IX_Semester_disciplines_Discipline_id");

                    b.HasIndex(new[] { "SemesterId" }, "IX_Semester_disciplines_Semester_id");

                    b.ToTable("Semester_disciplines");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Street", b =>
                {
                    b.Property<int>("StreetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Street_id");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("City_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("StreetId");

                    b.HasIndex("CityId");

                    b.ToTable("Streets");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Audience", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.AudienceType", "AudienceType")
                        .WithMany("Audiences")
                        .HasForeignKey("AudienceTypeId")
                        .HasConstraintName("FK_Audiences_Audience_types");

                    b.HasOne("EducationProcess.DataAccess.Entities.Department", "Department")
                        .WithMany("Audiences")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Audiences_Departments")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.Employee", "EmployeeHead")
                        .WithMany("Audiences")
                        .HasForeignKey("EmployeeHeadId")
                        .HasConstraintName("FK_Audiences_Employees");

                    b.Navigation("AudienceType");

                    b.Navigation("Department");

                    b.Navigation("EmployeeHead");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.CathedraSpecialty", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.Cathedra", "Cathedra")
                        .WithMany("CathedraSpecialties")
                        .HasForeignKey("CathedraId")
                        .HasConstraintName("FK_Cathedra_specialties_Cathedras")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.FsesCategoryPartition", "FsesCategoryPatition")
                        .WithMany("CathedraSpecialties")
                        .HasForeignKey("FsesCategoryPartitionId")
                        .HasConstraintName("FK_Cathedra_specialties_Fses_category_partitions")
                        .IsRequired();

                    b.Navigation("Cathedra");

                    b.Navigation("FsesCategoryPatition");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.City", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .HasConstraintName("FK_Cities_Regions");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ConductedPair", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.LessonType", "LessonType")
                        .WithMany("ConductedPairs")
                        .HasForeignKey("LessonTypeId")
                        .HasConstraintName("FK_Conducted_pairs_Lesson_types")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.ScheduleDiscipline", "ScheduleDiscipline")
                        .WithMany("ConductedPairs")
                        .HasForeignKey("ScheduleDisciplineId")
                        .HasConstraintName("FK_Conducted_pairs_Schedule_disciplines1");

                    b.HasOne("EducationProcess.DataAccess.Entities.ScheduleDisciplineReplacement", "ScheduleDisciplineReplacement")
                        .WithMany("ConductedPairs")
                        .HasForeignKey("ScheduleDisciplineReplacementId")
                        .HasConstraintName("FK_Conducted_pairs_Schedule_discipline_replacement");

                    b.Navigation("LessonType");

                    b.Navigation("ScheduleDiscipline");

                    b.Navigation("ScheduleDisciplineReplacement");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Department", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.Street", "Street")
                        .WithMany("Departments")
                        .HasForeignKey("StreetId")
                        .HasConstraintName("FK_Departments_Streets")
                        .IsRequired();

                    b.Navigation("Street");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Discipline", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.Cathedra", "Cathedra")
                        .WithMany("Disciplines")
                        .HasForeignKey("CathedraId")
                        .HasConstraintName("FK_Disciplines_Cathedras");

                    b.HasOne("EducationProcess.DataAccess.Entities.EducationCyclesAndModule", "EducationCycle")
                        .WithMany("Disciplines")
                        .HasForeignKey("EducationCycleId")
                        .HasConstraintName("FK_Disciplines_Education_cycles_and_modules")
                        .IsRequired();

                    b.Navigation("Cathedra");

                    b.Navigation("EducationCycle");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EducationCyclesAndModule", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.EducationCyclesAndModule", "EducationCycleParent")
                        .WithMany("InverseEducationCycleParent")
                        .HasForeignKey("EducationCycleParentId")
                        .HasConstraintName("FK_Education_cycles_and_modules_Education_cycles_and_modules");

                    b.Navigation("EducationCycleParent");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EducationPlan", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.AcademicYear", "AcademicYear")
                        .WithMany("EducationPlans")
                        .HasForeignKey("AcademicYearId")
                        .HasConstraintName("FK_Education_plans_Academic_years")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.FsesCategoryPartition", "FsesCategoryPatition")
                        .WithMany("EducationPlans")
                        .HasForeignKey("FsesCategoryPartitionId")
                        .HasConstraintName("FK_Education_plans_Fses_category_partitions")
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("FsesCategoryPatition");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EducationPlanSemesterDiscipline", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.EducationPlan", "EducationPlan")
                        .WithMany("EducationPlanSemesterDisciplines")
                        .HasForeignKey("EducationPlanId")
                        .HasConstraintName("FK_Education_plan_semester_disciplines_Education_plans")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.SemesterDiscipline", "SemesterDiscipline")
                        .WithMany("EducationPlanSemesterDisciplines")
                        .HasForeignKey("SemesterDisciplineId")
                        .HasConstraintName("FK_Education_plan_semester_disciplines_Semester_disciplines")
                        .IsRequired();

                    b.Navigation("EducationPlan");

                    b.Navigation("SemesterDiscipline");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Employee", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Employees_Departments")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.Post", "Post")
                        .WithMany("Employees")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_Employees_Posts")
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EmployeeCathedra", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.Cathedra", "Cathedra")
                        .WithMany("EmployeeCathedras")
                        .HasForeignKey("CathedraId")
                        .HasConstraintName("FK_Employee_cathedras_Cathedras")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.Employee", "Employee")
                        .WithMany("EmployeeCathedras")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Employee_cathedras_Employees")
                        .IsRequired();

                    b.Navigation("Cathedra");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.FixedDiscipline", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.Employee", "FixerEmployee")
                        .WithMany("FixedDisciplineFixerEmployees")
                        .HasForeignKey("FixerEmployeeId")
                        .HasConstraintName("FK_Fixed_disciplines_Employees1")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.Employee", "FixingEmployee")
                        .WithMany("FixedDisciplineFixingEmployees")
                        .HasForeignKey("FixingEmployeeId")
                        .HasConstraintName("FK_Fixed_disciplines_Employees")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.Group", "Group")
                        .WithMany("FixedDisciplines")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_Fixed_disciplines_Groups")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.SemesterDiscipline", "SemesterDiscipline")
                        .WithMany("FixedDisciplines")
                        .HasForeignKey("SemesterDisciplineId")
                        .HasConstraintName("FK_Fixed_disciplines_Semester_disciplines")
                        .IsRequired();

                    b.Navigation("FixerEmployee");

                    b.Navigation("FixingEmployee");

                    b.Navigation("Group");

                    b.Navigation("SemesterDiscipline");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.FsesCategory", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.FederalStateEducationalStandard", "Fses")
                        .WithMany("FsesCategories")
                        .HasForeignKey("FsesId")
                        .HasConstraintName("FK_Fses_categories_Federal_state_educational_standards")
                        .IsRequired();

                    b.Navigation("Fses");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.FsesCategoryPartition", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.FsesCategory", "FsesCategory")
                        .WithMany("FsesCategoryPartitions")
                        .HasForeignKey("FsesCategoryId")
                        .HasConstraintName("FK_Fses_category_partitions_Fses_categories")
                        .IsRequired();

                    b.Navigation("FsesCategory");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Group", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.Employee", "Curator")
                        .WithMany("Groups")
                        .HasForeignKey("CuratorId")
                        .HasConstraintName("FK_Groups_Employees");

                    b.HasOne("EducationProcess.DataAccess.Entities.Department", "Department")
                        .WithMany("Groups")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Groups_Departments")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.EducationPlan", "EducationPlan")
                        .WithMany("Groups")
                        .HasForeignKey("EducationPlanId")
                        .HasConstraintName("FK_Groups_Education_plans");

                    b.HasOne("EducationProcess.DataAccess.Entities.ReceivedEducation", "ReceivedEducation")
                        .WithMany("Groups")
                        .HasForeignKey("ReceivedEducationId")
                        .HasConstraintName("FK_Groups_Received_educations")
                        .IsRequired();

                    b.Navigation("Curator");

                    b.Navigation("Department");

                    b.Navigation("EducationPlan");

                    b.Navigation("ReceivedEducation");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ReceivedEducation", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.EducationLevel", "EducationLevel")
                        .WithMany("ReceivedEducations")
                        .HasForeignKey("EducationLevelId")
                        .HasConstraintName("FK_Received_educations_Education_levels")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.ReceivedEducationForm", "ReceivedEducationForm")
                        .WithMany("ReceivedEducations")
                        .HasForeignKey("ReceivedEducationFormId")
                        .HasConstraintName("FK_Received_educations_Received_education_forms")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.ReceivedSpecialty", "ReceivedSpecialty")
                        .WithMany("ReceivedEducations")
                        .HasForeignKey("ReceivedSpecialtyId")
                        .HasConstraintName("FK_Received_educations_Received_specialties")
                        .IsRequired();

                    b.Navigation("EducationLevel");

                    b.Navigation("ReceivedEducationForm");

                    b.Navigation("ReceivedSpecialty");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ReceivedEducationForm", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.EducationForm", "EducationForm")
                        .WithMany("ReceivedEducationForms")
                        .HasForeignKey("EducationFormId")
                        .HasConstraintName("FK_Received_education_forms_Education_forms")
                        .IsRequired();

                    b.Navigation("EducationForm");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ReceivedSpecialty", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.FsesCategoryPartition", "FsesCategoryPatition")
                        .WithMany("ReceivedSpecialties")
                        .HasForeignKey("FsesCategoryPartitionId")
                        .HasConstraintName("FK_Received_specialties_Fses_category_partitions")
                        .IsRequired();

                    b.Navigation("FsesCategoryPatition");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ScheduleDiscipline", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.Audience", "Audience")
                        .WithMany("ScheduleDisciplines")
                        .HasForeignKey("AudienceId")
                        .HasConstraintName("FK_Schedule_disciplines_Audiences");

                    b.HasOne("EducationProcess.DataAccess.Entities.Employee", "CreatedByEmployee")
                        .WithMany("ScheduleDisciplineCreatedByEmployees")
                        .HasForeignKey("CreatedByEmployeeId")
                        .HasConstraintName("FK_Schedule_disciplines_Employees")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.FixedDiscipline", "FixedDiscipline")
                        .WithMany("ScheduleDisciplines")
                        .HasForeignKey("FixedDisciplineId")
                        .HasConstraintName("FK_Schedule_disciplines_Fixed_disciplines")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.Employee", "ModifiedByEmployee")
                        .WithMany("ScheduleDisciplineModifiedByEmployees")
                        .HasForeignKey("ModifiedByEmployeeId")
                        .HasConstraintName("FK_Schedule_disciplines_Employees1")
                        .IsRequired();

                    b.Navigation("Audience");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("FixedDiscipline");

                    b.Navigation("ModifiedByEmployee");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ScheduleDisciplineReplacement", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.Audience", "Audience")
                        .WithMany("ScheduleDisciplineReplacements")
                        .HasForeignKey("AudienceId")
                        .HasConstraintName("FK_Schedule_discipline_replacement_Audiences");

                    b.HasOne("EducationProcess.DataAccess.Entities.Employee", "CreatedByEmployee")
                        .WithMany("ScheduleDisciplineReplacementCreatedByEmployees")
                        .HasForeignKey("CreatedByEmployeeId")
                        .HasConstraintName("FK_Schedule_discipline_replacement_Employees")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.FixedDiscipline", "FixedDiscipline")
                        .WithMany("ScheduleDisciplineReplacements")
                        .HasForeignKey("FixedDisciplineId")
                        .HasConstraintName("FK_Schedule_discipline_replacement_Fixed_disciplines")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.Employee", "ModifiedByEmployee")
                        .WithMany("ScheduleDisciplineReplacementModifiedByEmployees")
                        .HasForeignKey("ModifiedByEmployeeId")
                        .HasConstraintName("FK_Schedule_discipline_replacement_Employees1")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.ScheduleDiscipline", "ScheduleDiscipline")
                        .WithMany("ScheduleDisciplineReplacements")
                        .HasForeignKey("ScheduleDisciplineId")
                        .HasConstraintName("FK_Schedule_discipline_replacement_Schedule_disciplines");

                    b.Navigation("Audience");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("FixedDiscipline");

                    b.Navigation("ModifiedByEmployee");

                    b.Navigation("ScheduleDiscipline");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.SemesterDiscipline", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.IntermediateCertificationForm", "CertificationForm")
                        .WithMany("SemesterDisciplines")
                        .HasForeignKey("CertificationFormId")
                        .HasConstraintName("FK_Semester_disciplines_Intermediate_certification_forms");

                    b.HasOne("EducationProcess.DataAccess.Entities.Discipline", "Discipline")
                        .WithMany("SemesterDisciplines")
                        .HasForeignKey("DisciplineId")
                        .HasConstraintName("FK_Semesters_Disciplines_Disciplines")
                        .IsRequired();

                    b.HasOne("EducationProcess.DataAccess.Entities.Semester", "Semester")
                        .WithMany("SemesterDisciplines")
                        .HasForeignKey("SemesterId")
                        .HasConstraintName("FK_Semesters_Disciplines_Semesters")
                        .IsRequired();

                    b.Navigation("CertificationForm");

                    b.Navigation("Discipline");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Street", b =>
                {
                    b.HasOne("EducationProcess.DataAccess.Entities.City", "City")
                        .WithMany("Streets")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Streets_Cities")
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.AcademicYear", b =>
                {
                    b.Navigation("EducationPlans");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Audience", b =>
                {
                    b.Navigation("ScheduleDisciplineReplacements");

                    b.Navigation("ScheduleDisciplines");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.AudienceType", b =>
                {
                    b.Navigation("Audiences");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Cathedra", b =>
                {
                    b.Navigation("CathedraSpecialties");

                    b.Navigation("Disciplines");

                    b.Navigation("EmployeeCathedras");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.City", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Department", b =>
                {
                    b.Navigation("Audiences");

                    b.Navigation("Employees");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Discipline", b =>
                {
                    b.Navigation("SemesterDisciplines");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EducationCyclesAndModule", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("InverseEducationCycleParent");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EducationForm", b =>
                {
                    b.Navigation("ReceivedEducationForms");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EducationLevel", b =>
                {
                    b.Navigation("ReceivedEducations");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.EducationPlan", b =>
                {
                    b.Navigation("EducationPlanSemesterDisciplines");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Employee", b =>
                {
                    b.Navigation("Audiences");

                    b.Navigation("EmployeeCathedras");

                    b.Navigation("FixedDisciplineFixerEmployees");

                    b.Navigation("FixedDisciplineFixingEmployees");

                    b.Navigation("Groups");

                    b.Navigation("ScheduleDisciplineCreatedByEmployees");

                    b.Navigation("ScheduleDisciplineModifiedByEmployees");

                    b.Navigation("ScheduleDisciplineReplacementCreatedByEmployees");

                    b.Navigation("ScheduleDisciplineReplacementModifiedByEmployees");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.FederalStateEducationalStandard", b =>
                {
                    b.Navigation("FsesCategories");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.FixedDiscipline", b =>
                {
                    b.Navigation("ScheduleDisciplineReplacements");

                    b.Navigation("ScheduleDisciplines");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.FsesCategory", b =>
                {
                    b.Navigation("FsesCategoryPartitions");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.FsesCategoryPartition", b =>
                {
                    b.Navigation("CathedraSpecialties");

                    b.Navigation("EducationPlans");

                    b.Navigation("ReceivedSpecialties");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Group", b =>
                {
                    b.Navigation("FixedDisciplines");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.IntermediateCertificationForm", b =>
                {
                    b.Navigation("SemesterDisciplines");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.LessonType", b =>
                {
                    b.Navigation("ConductedPairs");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Post", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ReceivedEducation", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ReceivedEducationForm", b =>
                {
                    b.Navigation("ReceivedEducations");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ReceivedSpecialty", b =>
                {
                    b.Navigation("ReceivedEducations");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Region", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ScheduleDiscipline", b =>
                {
                    b.Navigation("ConductedPairs");

                    b.Navigation("ScheduleDisciplineReplacements");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.ScheduleDisciplineReplacement", b =>
                {
                    b.Navigation("ConductedPairs");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Semester", b =>
                {
                    b.Navigation("SemesterDisciplines");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.SemesterDiscipline", b =>
                {
                    b.Navigation("EducationPlanSemesterDisciplines");

                    b.Navigation("FixedDisciplines");
                });

            modelBuilder.Entity("EducationProcess.DataAccess.Entities.Street", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
